name: maigensawyer
favicon: null
layout_spectrum: 0.22739331633783877
typography_spectrum: 0.1991808689199388
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5511620729230344
  lightness: 0.17308374075219035
  saturation: 0.8526321221143007
  rhythmicContrast: 0.16749559226445854
purpose: []
